# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_music_randomizer"

# Version of this mod.
version = "0.1.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "MM Music Randomizer"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This mod reads .mmrs files created for ZoeyZoltova's emulated randomizer and (WIP) randomizes music. 
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "MMRS reader and randomizer"

# Authors of this mod.
authors = [ "Asticky" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
   "magemods_audio_api",
   "mm_recomp_rando",
   "ProxyMM_KV:0.0.5"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
   { name = "mm_recomp_mmrs_reader_extlib", funcs = ["set_log_level", "sql_init", "read_mmrs_files", "load_mmrs_table", "load_zseq", "load_zbank", "sql_teardown", "get_current_time", "fucking_use_stoi", "count_zsound", "load_zsounds", "zsound_key_add", "zsound_key_remove", "zsound_key_lookup"] },
   { name = "APCpp-Glue", funcs = ["rando_get_seed_name", "rando_solo_generate"]}
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_music_randomizer"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.png" ]

# Info for building the extlib. If this mod will have no extlib, remove this section and
# the build scripts disable extlib compilation and packaging. You can then safely delete 
# ./CMakeLists.txt, ./CMakePresets.json, and ./src/extlib/**
[extlib_compiling]

# # Name of the extlib. This information is passed to CMake as the target name for the extlib.
library_name = "mm_recomp_mmrs_reader_extlib"

# Your CMake presets in this file should be designed to handle cross-compilation (using the provided
# Zig toolchain is recommended). When building the mod, CMake will be invoked 3 times to build
# extlib binaries for Windows, Macos, and Linux. The presets below are used to contruct 
# `user_build_config.json` (if it isn't present already), which is read to determine what CMake
# presets to use. The presets are organized in to groups, with each group containing "Windows", 
# "Macos", "Linux", and "Native" presets (more on the native preset below). The "Debug" preset group
# is the default, and the "Release" group is used by `create_thunderstore_package.py` when creating
# the Thunderstore release. You can also add more groups, using the make variable `EXTLIB_CMAKE_PRESET_GROUP`
# to choose the group when invoking make. You can change the presets in `user_build_config.json` in order use 
# build with non-default presets locally (presets from `CMakeUserPresets.json`, for example) without modifying 
# defaults here.

# "Native" presets are for building your mod using your local system tools/toolchain instead of cross-compilation. 
# This can be a useful feature for debugging. The build scripts will automatically select default native
# presets suitable for your system when creating your `user_build_config.json` file, and you can easily
# add new presets to `CMakePresets.json` or `CMakeUserPresets.json` for further expansion. Use `make native`
# to run a native build. You can also select what presets you wish to use for your native build by assigning
# the make variables `NATIVE_CMAKE_CONFIGURE_PRESET` and `NATIVE_CMAKE_BUILD_PRESET`.

# CMake presets for Debug builds. 
windows_debug_configure_preset = "zig-windows-x64-Debug"
windows_debug_build_preset = "zig-windows-x64-Debug"

macos_debug_configure_preset = "zig-macos-aarch64-Debug"
macos_debug_build_preset = "zig-macos-aarch64-Debug"

linux_debug_configure_preset = "zig-linux-x64-Debug"
linux_debug_build_preset = "zig-linux-x64-Debug"

# CMake presets for Release builds. Used to contruct preset groups in `user_build_config.json`.
windows_release_configure_preset = "zig-windows-x64-Release"
windows_release_build_preset = "zig-windows-x64-Release"

macos_release_configure_preset = "zig-macos-aarch64-Release"
macos_release_build_preset = "zig-macos-aarch64-Release"

linux_release_configure_preset = "zig-linux-x64-Release"
linux_release_build_preset = "zig-linux-x64-Release"

# Mod config options
[[manifest.config_options]]

id = "log_level"
name = "Log Level"
description = "Controls the verbosity output to the console. Only affects debug releases."
type = "Enum"
options = [ "Nothing", "Critical", "Error", "Warning", "Info", "Debug" ]
default = "Error"

[[manifest.config_options]]

id = "disable_enemy_bgm"
name = "Disable Combat Music"
description = "Controls whether combat music plays while fighting a normal enemy. Does not apply to (mini-)bosses."
type = "Enum"
options = [ "Off", "On" ]
default = "Off"

[[manifest.config_options]]

id = "show_song_titles"
name = "Show Song Titles"
description = "Controls whether the songs' titles are displayed on screen."
type = "Enum"
options = [ "Off", "On" ]
default = "On"